apiVersion: v1
kind: Service
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  type: LoadBalancer
  selector:
    app: go-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000 
#status:
#  loadBalancer: {}